- build: 0.5.4
  image:
    - mesoscloud/events:0.5.4
    - mesoscloud/events:latest

- build: 0.5.3
  image:
    - mesoscloud/events:0.5.3

- build: 0.5.2
  image:
    - mesoscloud/events:0.5.2

- build: 0.5.1
  image:
    - mesoscloud/events:0.5.1

- build: 0.5.0
  image:
    - mesoscloud/events:0.5.0

- build: 0.4.2
  image:
    - mesoscloud/events:0.4.2

- build: 0.4.1
  image:
    - mesoscloud/events:0.4.1

- build: 0.4.0
  image:
    - mesoscloud/events:0.4.0


- tests:
    - cmd: python -m doctest ./*.py
